server:
  port: 8080

mock-backend:
  enabled: true
  port: 8001
  path: moculus-bucket

management:
  port: 8081
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
        exclude: env,beans
  statsd:
    metrics:
      export:
        enabled: false
        host: localhost
