server:
  enabled: false
  port: 8080

# uncomment to disable embedded API server
#spring:
#  main:
#    web-application-type: none

mock-backend:
  enabled: true
  port: 8001
  path: moculus-bucket

aws:
  accessKeyId:
  secretAccessKey:

management:
  port: 8081
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: metrics,prometheus
        exclude:
  statsd:
    metrics:
      export:
        enabled: false
        host: localhost
